package ai

import (
	"backend/pkg/types"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
)

const DefaultModel = "openai/gpt-5.4-nano"
const OpenRouterURL = "https://openrouter.ai/api/v1/chat/completions"

const tagSelectorPrompt = `
You are an intelligent tag selector. You have the following list of tags:

%v

When I give you a short description or a sentence about an item I need (for example, "my car has broken"), you will return **only the relevant tags from the above list** that specifically describe the item, separated by commas, without extra explanation.  

Example:  
Input: "I need a new pair of running shoes for jogging"  
Output: "fitness, sport, scarpe"  

Input: "I want a laptop with good battery life and lightweight"  
Output: "laptop, ultrabook, batteria, pc"  

Now process the following input and give me only the matching tags:  
%s`

const aiTransparencyPrompt = `
You are giving an honest and transparent answer to the user.
The user has searched the following item description: %s

You have decided that the search query has the following tags: %v
You have decided that the item that best matches the tags is: %s
The item has the following description: %s

Now, explain to the user in a clear and concise way why you chose this item, how the tags relate to the item, and how the item matches the user's search query. Be honest about any limitations or uncertainties in your reasoning. Avoid technical jargon and be as transparent as possible.
Be concise and focus on the most relevant information to help the user understand your decision.
The tags were generated by you and not the user and as such keep it short and write them discursively and not in a program way.
Do not make a list of arguments in any way, do not use bullet points, do not use numbers, do not use commas to separate the tags, just write them in a natural way as if you were explaining your reasoning to a friend.
Be extremely short and concise, ideally one or two sentences, and do not repeat the item name, the item type or the item description in the explanation.
`

func tagPrompt(dbTags []string, userInput string) string {
	return fmt.Sprintf(tagSelectorPrompt, dbTags, userInput)
}

func QuestionAI(appState *types.AppContext, ctx context.Context, model string, question string) (string, error) {
	payload := map[string]interface{}{
		"model": model,
		"messages": []map[string]string{
			{"role": "user", "content": question},
		},
		"temperature": 0.2,
	}

	jsonBody, _ := json.Marshal(payload)

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, OpenRouterURL, bytes.NewBuffer(jsonBody))
	if err != nil {
		return "", err
	}
	req.Header.Set("Authorization", "Bearer "+appState.GetConfig().GetAPIKey())
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("OpenRouter API error (status %d): %s", resp.StatusCode, string(respBody))
	}

	var res struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err = json.Unmarshal(respBody, &res); err != nil {
		return "", err
	}

	if len(res.Choices) == 0 {
		return "", fmt.Errorf("no response from AI")
	}

	return strings.TrimSpace(res.Choices[0].Message.Content), nil
}

func TransparencyFromPrompt(appState *types.AppContext, ctx context.Context, model string, userQuery string, tags []string, itemName string, itemDescription string) (string, error) {
	if model == "" {
		model = DefaultModel
	}

	aiPrompt := fmt.Sprintf(aiTransparencyPrompt, userQuery, tags, itemName, itemDescription)
	return QuestionAI(appState, ctx, model, aiPrompt)
}

func TagsFromPrompt(appState *types.AppContext, ctx context.Context, model string, dbTags []string, userPrompt string) ([]string, error) {
	if model == "" {
		model = DefaultModel
	}

	aiPrompt := tagPrompt(dbTags, userPrompt)
	res, err := QuestionAI(appState, ctx, model, aiPrompt)
	if err != nil {
		return nil, err
	}

	return splitTags(res), nil
}

func splitTags(s string) []string {
	s = strings.TrimSpace(s)
	if s == "" {
		return nil
	}
	var out []string
	for _, part := range strings.FieldsFunc(s, func(r rune) bool {
		return r == ',' || r == '\n'
	}) {
		t := strings.TrimSpace(part)
		if t != "" {
			out = append(out, t)
		}
	}
	return out
}
